@extends('pdf.layout')

@section('title', 'Audit Logs')

@section('content')
<style>
    .rpt-title-block { margin-bottom: 12px; border-bottom: 2px solid #0f172a; padding-bottom: 8px; }
    .rpt-company     { font-size: 13pt; font-weight: bold; color: #0f172a; }
    .rpt-doc-title   { font-size: 9pt; text-transform: uppercase; letter-spacing: 2px; color: #475569; font-weight: bold; margin-top: 2px; }
    .rpt-meta        { font-size: 8pt; color: #64748b; margin-top: 2px; }

    table.audit-tbl { width: 100%; border-collapse: collapse; font-size: 7.5pt; margin-top: 4px; }
    table.audit-tbl thead th {
        background: #1e293b; color: #f8fafc; padding: 5px 6px; text-align: left;
        font-size: 6.8pt; text-transform: uppercase; letter-spacing: 0.6px; font-weight: bold;
    }
    table.audit-tbl tbody td {
        padding: 4px 6px; border-bottom: 1px solid #e5e7eb; color: #1f2937; vertical-align: top;
    }
    table.audit-tbl tbody tr:nth-child(even) td { background: #fafafa; }
    .changes { color: #475569; font-size: 7pt; }
</style>

<div class="rpt-title-block">
    <div class="rpt-company">{{ $company->name ?? 'Company' }}</div>
    <div class="rpt-doc-title">Audit Log Report</div>
    <div class="rpt-meta">Generated by {{ $generatedBy }} on {{ $generatedAt->format('d M Y, H:i') }} · {{ $logs->count() }} entries</div>
</div>

<table class="audit-tbl">
    <thead>
        <tr>
            <th style="width: 12%;">When</th>
            <th style="width: 11%;">User</th>
            <th style="width: 8%;">Action</th>
            <th style="width: 11%;">Module</th>
            <th style="width: 14%;">Record</th>
            <th style="width: 10%;">Branch</th>
            <th>Changes</th>
        </tr>
    </thead>
    <tbody>
        @php
            $scalar = function ($v, $k = '') use ($fkLabels) {
                if (is_null($v)) return '';
                if (is_bool($v)) return $v ? 'true' : 'false';
                if (is_array($v)) return json_encode($v);
                if (is_numeric($v) && isset($fkLabels[$k][(int) $v])) return $fkLabels[$k][(int) $v] . ' (#' . $v . ')';
                return (string) $v;
            };
        @endphp
        @forelse ($logs as $log)
            @php
                $old = $log->old_values ?? [];
                $new = $log->new_values ?? [];
                $keys = array_values(array_unique(array_merge(array_keys($old), array_keys($new))));
                $summary = [];
                foreach ($keys as $k) {
                    $b = array_key_exists($k, $old) ? $scalar($old[$k], $k) : '';
                    $a = array_key_exists($k, $new) ? $scalar($new[$k], $k) : '';
                    $summary[] = $k . ': ' . $b . ' → ' . $a;
                }
                $recLabel = $recordLabels[$log->auditable_type . ':' . $log->auditable_id] ?? null;
            @endphp
            <tr>
                <td>{{ $log->created_at?->format('d M Y H:i') }}</td>
                <td>{{ $log->actorName() }}</td>
                <td>{{ ucwords(str_replace('_', ' ', $log->event)) }}</td>
                <td>{{ \App\Services\AuditLogService::label($log->auditable_type) }}</td>
                <td>{{ $recLabel ? $recLabel . ' (#' . $log->auditable_id . ')' : '#' . $log->auditable_id }}</td>
                <td>{{ $log->outlet?->name ?? '—' }}</td>
                <td class="changes">{{ implode('; ', $summary) }}</td>
            </tr>
        @empty
            <tr><td colspan="7" style="text-align:center; padding: 14px; color:#94a3b8;">No audit entries match these filters.</td></tr>
        @endforelse
    </tbody>
</table>
@endsection
