@extends('pdf.layout')

@section('title', 'OT Claims Summary — ' . $periodLabel)

@section('content')
<style>
    .rpt-title-block { margin-bottom: 14px; border-bottom: 2px solid #0f172a; padding-bottom: 10px; }
    .rpt-company     { font-size: 13pt; font-weight: bold; color: #0f172a; }
    .rpt-doc-title   { font-size: 9.5pt; text-transform: uppercase; letter-spacing: 2px; color: #475569; font-weight: bold; margin-top: 2px; }
    .rpt-period      { font-size: 8.5pt; color: #64748b; margin-top: 2px; }

    table.ot-tbl { width: 100%; border-collapse: collapse; font-size: 9pt; margin-top: 2px; }

    table.ot-tbl thead th {
        background: #1e293b;
        color: #f8fafc;
        padding: 7px 8px;
        text-align: left;
        font-size: 7.5pt;
        text-transform: uppercase;
        letter-spacing: 0.8px;
        font-weight: bold;
    }
    table.ot-tbl thead th.right  { text-align: right; }
    table.ot-tbl thead th.center { text-align: center; }

    /* Regular data rows */
    table.ot-tbl tbody td {
        padding: 6px 8px;
        border-bottom: 1px solid #e5e7eb;
        color: #1f2937;
        vertical-align: middle;
    }
    table.ot-tbl tbody td.right  { text-align: right; }
    table.ot-tbl tbody td.center { text-align: center; }

    /* Continuation rows (2nd, 3rd OT type for same employee) */
    table.ot-tbl tbody tr.cont-row td { background: #fafafa; }

    /* Employee total row */
    table.ot-tbl tbody tr.emp-total td {
        background: #f1f5f9;
        border-top: 1px solid #cbd5e1;
        border-bottom: 2px solid #94a3b8;
        font-weight: bold;
        font-size: 8.5pt;
        color: #334155;
        padding: 5px 8px;
    }
    table.ot-tbl tbody tr.emp-total td.right { text-align: right; }

    /* Grand total footer */
    table.ot-tbl tfoot td {
        background: #1e293b;
        color: #f8fafc;
        font-weight: bold;
        font-size: 9.5pt;
        padding: 8px 8px;
        border-top: 2px solid #0f172a;
    }
    table.ot-tbl tfoot td.right { text-align: right; }
</style>

{{-- Report header --}}
<table style="width:100%; border-collapse:collapse;" class="rpt-title-block">
    <tr>
        <td style="vertical-align:middle; width:65%;">
            @if ($company?->logo_url)
                <img src="{{ public_path('storage/' . ltrim(parse_url($company->logo_url, PHP_URL_PATH), '/storage/')) }}"
                     style="max-height:40px; max-width:130px; display:block; margin-bottom:5px;">
            @endif
            <div class="rpt-company">{{ $company?->name ?? 'Servora' }}</div>
            <div class="rpt-doc-title">Overtime Claims — Summary Report</div>
            <div class="rpt-period">Period: {{ $periodLabel }}</div>
        </td>
        <td style="vertical-align:middle; text-align:right; width:35%;">
            <div style="font-size:7.5pt; color:#94a3b8;">Generated by</div>
            <div style="font-size:9pt; font-weight:bold; color:#1e293b;">{{ $exportedBy }}</div>
            <div style="font-size:7.5pt; color:#94a3b8; margin-top:2px;">{{ now()->format('d M Y, h:i A') }}</div>
        </td>
    </tr>
</table>

@if ($rows->isEmpty())
    <div style="text-align:center; padding:40px 0; color:#94a3b8; font-size:10pt; font-style:italic;">
        No approved overtime claims found for {{ $periodLabel }}.
    </div>
@else
    <table class="ot-tbl">
        <thead>
            <tr>
                <th style="width:30px;" class="center">No.</th>
                <th>Employee Name</th>
                <th style="width:80px;">Staff ID</th>
                <th style="width:110px;">Designation</th>
                <th style="width:110px;">OT Type</th>
                <th style="width:70px;" class="right">OT Hours</th>
                <th style="width:80px;" class="right">Total OT Hours</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($rows as $i => $row)
                @php
                    $emp      = $row['employee'];
                    $byType   = $row['byType'];
                    $total    = $row['totalHours'];
                    $rowCount = $byType->count();
                @endphp

                @foreach ($byType as $ti => $typeRow)
                    <tr class="{{ $ti > 0 ? 'cont-row' : '' }}">
                        {{-- No. — only on first OT type row for this employee --}}
                        <td class="center" style="color:#94a3b8; font-size:8pt;">
                            @if ($ti === 0) {{ $i + 1 }} @endif
                        </td>

                        {{-- Employee Name — only on first row --}}
                        <td style="font-weight:{{ $ti === 0 ? '600' : '400' }}; color:{{ $ti === 0 ? '#0f172a' : '#9ca3af' }};">
                            @if ($ti === 0)
                                {{ $emp?->name ?? '—' }}
                            @else
                                &nbsp;
                            @endif
                        </td>

                        {{-- Staff ID — only on first row --}}
                        <td style="font-size:8.5pt; color:{{ $ti === 0 ? '#475569' : '#d1d5db' }};">
                            @if ($ti === 0) {{ $emp?->staff_id ?? '—' }} @endif
                        </td>

                        {{-- Designation — only on first row --}}
                        <td style="font-size:8.5pt; color:{{ $ti === 0 ? '#475569' : '#d1d5db' }};">
                            @if ($ti === 0) {{ $emp?->designation ?? '—' }} @endif
                        </td>

                        {{-- OT Type --}}
                        <td style="font-size:8.5pt; color:#334155;">{{ $typeRow['label'] }}</td>

                        {{-- OT Hours for this type --}}
                        <td class="right" style="font-size:9pt;">{{ number_format($typeRow['hours'], 2) }}</td>

                        {{-- Total OT Hours — only on first row, spanning visually --}}
                        <td class="right" style="font-weight:700; font-size:9pt; color:#1e3a5f;">
                            @if ($ti === 0) {{ number_format($total, 2) }} @endif
                        </td>
                    </tr>
                @endforeach

                {{-- Thin separator between employees (skip after last) --}}
                @if (! $loop->last)
                    <tr style="height:1px;">
                        <td colspan="7" style="padding:0; border-bottom:2px solid #e5e7eb;"></td>
                    </tr>
                @endif
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align:right; font-size:8.5pt; color:#94a3b8; text-transform:uppercase; letter-spacing:1px;">
                    Grand Total &mdash; {{ $rows->count() }} {{ Str::plural('employee', $rows->count()) }}
                </td>
                <td class="right">—</td>
                <td class="right">{{ number_format($grandTotalHours, 2) }}</td>
            </tr>
        </tfoot>
    </table>
@endif
@endsection
