<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Price History</title>
    <style>
        /* Scoped reset — `html`/`*` must NOT be reset: dompdf implements
           @page margins via the root element. */
        body, div, span, h1, h2, h3, p, img, table, thead, tbody, tr, th, td { margin: 0; padding: 0; box-sizing: border-box; }
        @@page { margin: 14mm 12mm; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 8px; color: #1a1a1a; line-height: 1.35; }

        .header { display: table; width: 100%; margin-bottom: 8px; border-bottom: 1.5px solid #2d3748; padding-bottom: 6px; }
        .header-left { display: table-cell; vertical-align: middle; width: 55%; }
        .header-right { display: table-cell; vertical-align: middle; width: 45%; text-align: right; }
        .logo { max-height: 28px; max-width: 90px; margin-right: 6px; vertical-align: middle; }
        .brand { font-size: 11px; font-weight: bold; vertical-align: middle; }
        .title { font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 1.5px; color: #374151; }
        .meta { font-size: 7px; color: #6b7280; margin-top: 2px; }

        .summary { margin-bottom: 8px; font-size: 8px; color: #374151; }
        .summary strong { font-size: 9px; }

        table.grid { width: 100%; border-collapse: collapse; }
        table.grid th, table.grid td { border: 0.6px solid #cbd5e1; padding: 3px 4px; }
        thead th { background: #2d3748; color: #fff; font-size: 7px; text-transform: uppercase; letter-spacing: 0.3px; font-weight: bold; }
        td.r { text-align: right; }
        td.c { text-align: center; }
        .up   { color: #b91c1c; font-weight: bold; }
        .down { color: #15803d; font-weight: bold; }
        .src  { font-size: 6.5px; color: #64748b; }

        .footer { margin-top: 10px; padding-top: 4px; border-top: 1px solid #e2e8f0; font-size: 6.5px; color: #94a3b8; text-align: right; }
    </style>
</head>
<body>

    <div class="header">
        <div class="header-left">
            @if ($logoBase64)
                <img src="{{ $logoBase64 }}" class="logo" />
            @endif
            <span class="brand">{{ $brandName }}</span>
        </div>
        <div class="header-right">
            <div class="title">Market List Price History</div>
            <div class="meta">
                {{ implode(' · ', $filters) ?: 'All records' }}
            </div>
        </div>
    </div>

    <div class="summary">
        <strong>{{ $stats['total'] }}</strong> price change(s) —
        <span class="up">{{ $stats['increases'] }} up</span> /
        <span class="down">{{ $stats['decreases'] }} down</span> ·
        Net value change: <strong>{{ $stats['netAmount'] >= 0 ? '+' : '−' }}RM {{ number_format(abs($stats['netAmount']), 2) }}</strong>
        @if ($truncated)
            · <span class="up">Truncated at {{ \App\Http\Controllers\PriceHistoryExportController::MAX_ROWS }} rows — narrow the date range for the rest.</span>
        @endif
    </div>

    <table class="grid">
        <thead>
            <tr>
                <th style="width: 3%;">#</th>
                <th style="width: 9%;">Effective Date</th>
                <th style="width: 26%; text-align: left;">Product</th>
                <th style="width: 6%;">Unit</th>
                <th style="width: 20%; text-align: left;">Supplier</th>
                <th style="width: 9%;">Old Price</th>
                <th style="width: 9%;">New Price</th>
                <th style="width: 9%;">Change</th>
                <th style="width: 9%;">Source</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $i => $row)
                <tr>
                    <td class="c">{{ $i + 1 }}</td>
                    <td class="c">{{ \Carbon\Carbon::parse($row->effective_date)->format('d M Y') }}</td>
                    <td>{{ $row->ingredient_name }}</td>
                    <td class="c">{{ $row->uom_abbr }}</td>
                    <td>{{ $row->supplier_name ?? 'Manual edit' }}</td>
                    <td class="r">{{ number_format($row->prev_cost, 4) }}</td>
                    <td class="r">{{ number_format($row->cost, 4) }}</td>
                    <td class="c {{ $row->change_amt > 0 ? 'up' : 'down' }}">
                        {{ $row->change_amt > 0 ? '+' : '−' }}{{ $row->change_pct !== null ? number_format(abs($row->change_pct), 1) . '%' : number_format(abs($row->change_amt), 2) }}
                    </td>
                    <td class="c src">{{ str_replace('_', ' ', $row->source ?? '') }}</td>
                </tr>
            @empty
                <tr><td colspan="9" style="text-align: center; color: #94a3b8; padding: 10px;">No price changes in the selected range.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by Servora · {{ $brandName }} · {{ now()->format('d M Y, h:i A') }}
    </div>

</body>
</html>
