{{-- Sign-off block and footer, shared by both attendance exports. The
     distribution is signed in its own right now that it is its own document —
     it is the sheet somebody approves a payout against. --}}
    <div class="signatures">
        <div class="sig">
            <div class="sig-label">Prepared by:</div>
            <div class="sig-line">Name / Signature / Date</div>
        </div>
        <div class="sig">
            <div class="sig-label">Checked by:</div>
            <div class="sig-line">Name / Signature / Date</div>
        </div>
        <div class="sig">
            <div class="sig-label">Approved by:</div>
            <div class="sig-line">Name / Signature / Date</div>
        </div>
    </div>

    <div class="footer">
        Generated by Servora · {{ $brandName }} · {{ now()->format('d M Y, h:i A') }}
    </div>
